###############################################################################################
#########                           --Database Settings--                             #########
###############################################################################################
dbhost: 127.0.0.1:3307
dbname: secret
dbuser: admin
dbpass: 'supersecret'
